### ISSUE TITLE
Split up painless.software into separate roles

### ISSUE THREAD

**Issue by bittner** [painless-software/ansible-role-software#5]
Currently, it's difficult to easily configure which software should be installed by the role [painless.software](https://galaxy.ansible.com/painless/software).

The easiest, but cumbersome to remember, approach currently is to use tags, as [explained in the README](https://github.com/painless-software/ansible-role-software#example-playbook).

Splitting up the role into separate roles that are meant to be individually included will make it more straight-forward to configure a setup, e.g.

```yaml
# FILE: playbook.yml
---
- hosts: foo
  vars:
    - painless_printer_name: samsung-clx7110
  roles:
    - painless.software-desktop
    - painless.software-gnome
    - painless.software-virtualization
    - painless.gnome
```
To ensure that this role continues to be [installed easily](https://github.com/painless-software/ansible-role-software#prerequisites) with a single command we need to turn this role into a "meta role" and declare dependencies, e.g.

```yaml
# FILE: meta/main.yml
---
galaxy_info:
  description: Configure OpenShift persistent volumes
  license: GPLv3

dependencies:
  - src: git+https://github.com/painless-software/ansible-module-software-desktop.git
    version: v2.0.1
  - src: git+https://github.com/painless-software/ansible-module-software-gnome.git
    version: v2.2.0
  - src: git+https://github.com/painless-software/ansible-module-software-virtualization.git
    version: v2.0.0
```

(Real-life example: [appuio/ansible-role-openshift-localstorage](https://github.com/appuio/ansible-role-openshift-localstorage))
